[package]
name = "uiuifree-elastic"
version = "0.1.0"
edition = "2021"

authors = ["uiuifree"]
description = "My ElasticSearch Util"
license = "MIT"

[dependencies]
dotenv = "0.15"
elasticsearch = "7.14.0-alpha.1"
elastic-query-builder ="*"
elastic-parser ="*"


serde = "~1"
serde_json = "~1"
serde_derive = "1.0"
